query flashcards {
  flashcards {
    id
    question
    answer
    category
  }
}

query categories {
  categories {
    id
    category
  }
}

query subcategories {
  subcategories {
    id
    subcategory
  }
}

mutation createNotification($message: String!) {
  createNotification(message: $message)
}

mutation addFlashcard($question: String!, $answer: String!, $category: String) {
  addFlashcard(question: $question, answer: $answer, category: $category)
}

mutation addCategory($category: String!) {
  addCategory(category: $category)
}

mutation addSubcategory($subcategory: String!) {
  addSubcategory(subcategory: $subcategory)
}

subscription newNotification {
  newNotification
}
